# Generated by Django 5.1 on 2024-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dprt', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('env', models.CharField(max_length=50)),
                ('pc_name', models.CharField(max_length=100)),
                ('pc_ip', models.GenericIPAddressField()),
                ('hw_sn', models.CharField(max_length=100)),
                ('spa_no', models.CharField(max_length=50)),
                ('report_type', models.CharField(max_length=100)),
                ('hw_type', models.CharField(max_length=100)),
                ('hw_type_encode', models.CharField(max_length=200)),
                ('hw_model', models.CharField(max_length=100)),
                ('apps_sw', models.CharField(max_length=200)),
                ('report_desc', models.TextField()),
                ('act_taken', models.TextField(blank=True, null=True)),
                ('act_stat', models.CharField(max_length=50)),
                ('date_created', models.DateField()),
                ('time_created', models.TimeField()),
                ('date_action', models.DateField(blank=True, null=True)),
                ('time_action', models.TimeField(blank=True, null=True)),
                ('taken_by', models.CharField(max_length=100)),
                ('ftr_act', models.TextField(blank=True, null=True)),
                ('fu_act', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
